name: work flow test
on: push
permissions:
  contents: write
jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo 'Hello world'
      - name: checkout
        uses: actions/checkout@v3
      - name: list
        run: ls -a
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: /
